modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="emerald_armor__tools"
version="1.1.0"
displayName="Emerald Armor + Tools"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/BullfrogMods/minecraft-emerald-mod"
authors="Bullfrog, MCreator"
description="Adds emerald armor and tools to minecraft"

[[dependencies.emerald_armor__tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




